export const CART_LOADER = "CART_LOADER";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_FAIL = "ADD_TO_CART_FAIL";
export const DELETE_FROM_CART = "DELETE_FROM_CART";
export const PRODUCT_QUANTITY_INCREASE = "PRODUCT_QUANTITY_INCREASE";
export const PRODUCT_QUANTITY_DECREASE = "PRODUCT_QUANTITY_DECREASE";
export const CLEAR_CART = "CLEAR_CART";
export const ADD_SHIPPING_ADDRESS = "ADD_SHIPPING_ADDRESS";
