export const PRODUCT_LIST = "PRODUCT_LIST";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";
export const PRODUCT_LOADER = "PRODUCT_LOADER";

export const PRODUCT_DETAIL = "PRODUCT_DETAIL";
export const PRODUCT_DETAIL_FAIL = "PRODUCT_DETAIL_FAIL";

export const PRODUCT_CATEGORIES = "PRODUCT_CATEGORIES";
export const PRODUCT_CATEGORIES_FAIL = "PRODUCT_CATEGORIES_FAIL";

export const PRODUCT_LIST_BY_CATEGORY = "PRODUCT_LIST_BY_CATEGORY";
export const PRODUCT_LIST_BY_CATEGORY_FAIL = "PRODUCT_LIST_BY_CATEGORY_FAIL";

export const PRODUCT_LIST_WITH_MULTI_CATEGORY =
  "PRODUCT_LIST_WITH_MULTI_CATEGORY";
export const PRODUCT_LIST_WITH_MULTI_CATEGORY_FAIL =
  "PRODUCT_LIST_WITH_MULTI_CATEGORY_FAIL";

export const PLACE_ORDER_SUCCESS = "PLACE_ORDER_SUCCESS";
export const PLACE_ORDER_FAIL = "PLACE_ORDER_FAIL";
export const PLACE_ORDER_ERROR = "PLACE_ORDER_ERROR";

export const HOME_PAGE_PRODUCTS_BY_CATEGORY_I =
  "HOME_PAGE_PRODUCTS_BY_CATEGORY_I";
export const HOME_PAGE_PRODUCTS_BY_CATEGORY_I_ERROR =
  "HOME_PAGE_PRODUCTS_BY_CATEGORY_I_ERROR";
export const HOME_PAGE_PRODUCTS_BY_CATEGORY_II =
  "HOME_PAGE_PRODUCTS_BY_CATEGORY_II";
export const HOME_PAGE_PRODUCTS_BY_CATEGORY_II_ERROR =
  "HOME_PAGE_PRODUCTS_BY_CATEGORY_II_ERROR";
