export const PRODUCT_LIST = "PRODUCT_LIST";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";
export const PRODUCT_LOADER = "PRODUCT_LOADER";

export const PRODUCT_DETAIL = "PRODUCT_DETAIL";
export const PRODUCT_DETAIL_FAIL = "PRODUCT_DETAIL_FAIL";

export const PRODUCT_CATEGORIES = "PRODUCT_CATEGORIES";
export const PRODUCT_CATEGORIES_FAIL = "PRODUCT_CATEGORIES_FAIL";

export const PRODUCT_LIST_BY_CATEGORY = "PRODUCT_LIST_BY_CATEGORY";
export const PRODUCT_LIST_BY_CATEGORY_FAIL = "PRODUCT_LIST_BY_CATEGORY_FAIL";

export const PRODUCT_LIST_WITH_MULTI_CATEGORY =
  "PRODUCT_LIST_WITH_MULTI_CATEGORY";
export const PRODUCT_LIST_WITH_MULTI_CATEGORY_FAIL =
  "PRODUCT_LIST_WITH_MULTI_CATEGORY_FAIL";
