export const USER_LOADER = "USER_LOADER";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";
export const GET_CLIENT_PROFILE = "GET_CLIENT_PROFILE";
